In [10]:
#Importing and prinitng the test and train sets
import pandas as pd

train = pd.read_csv("train.csv")
test = pd.read_csv("test.csv")

print (train.shape, test.shape)

(19579, 3) (8392, 2)

In [ ]:
train.head() #Making sure that the model is properly importing the training set

        id                                               text author
0  id26305  This process, however, afforded me no means of...    EAP
1  id17569  It never once occurred to me that the fumbling...    HPL
2  id11008  In his left hand was a gold snuff box, from wh...    EAP
3  id27763  How lovely is spring As we looked from Windsor...    MWS
4  id12958  Finding nothing else, not even gold, the Super...    HPL

In [ ]:
test.head() #Making sure that the model is properly importing the test set

        id                                               text
0  id02310  Still, as I urged our leaving Ireland with suc...
1  id24541  If a fire wanted fanning, it could readily be ...
2  id00134  And when they had broken down the frail door t...
3  id27757  While I was thinking how I should possibly man...
4  id04081  I am not sure to what limit his knowledge may ...

In [ ]:
#Tokenize all the text in the training set
train['text'] = train['text'].apply(lambda x: x.split())